version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
      - redis
      - rabbitmq
    environment:
      POSTGRES_DATASOURCE_USERNAME: postgres
      POSTGRES_DATASOURCE_PASSWORD: example
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE_NAME: companymanager
      MONGO_PORT: 27017
      MONGODB_USERNAME: mongo
      MONGODB_PASSWORD: example
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: example
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 15692
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: example
    networks:
      - companymanager

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: companymanager
    networks:
      - companymanager

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - companymanager

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - companymanager

  rabbitmq:
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=example
    networks:
      - companymanager

networks:
  companymanager:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
